/** @type {import('tailwindcss').Config} */
export default {
	darkMode: 'class',
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				bg: 'var(--bg)',
				ink: 'var(--ink)',
				muted: 'var(--muted)',
				'body-2': 'var(--body-2)',
				'body-3': 'var(--body-3)',
				line: 'var(--line)',
				'line-strong': 'var(--line-strong)',
				card: 'var(--card)',
				surface: 'var(--surface)',
				chip: 'var(--chip)',
				'tag-edge': 'var(--tag-edge)',
				accent: 'var(--accent)',
				'accent-deep': 'var(--accent-deep)',
				'accent-ink': 'var(--accent-ink)',
				'accent-tint': 'var(--accent-tint)',
				'on-accent': 'var(--on-accent)',
				'tint-1': 'var(--tint-1)',
				'tint-2': 'var(--tint-2)',
				'tint-card': 'var(--tint-card)',
				'tint-card-ink': 'var(--tint-card-ink)',
				'invert-bg': 'var(--invert-bg)',
				'invert-fg': 'var(--invert-fg)',
				'invert-muted': 'var(--invert-muted)',
				'invert-edge': 'var(--invert-edge)',
				'invert-accent': 'var(--invert-accent)',
			},
			fontFamily: {
				sans: ['"Schibsted Grotesk"', 'system-ui', 'sans-serif'],
				display: ['Unbounded', 'system-ui', 'sans-serif'],
				mono: ['"Space Mono"', 'ui-monospace', 'monospace'],
			},
			borderRadius: {
				card: '22px',
			},
		},
	},
	plugins: [],
};
